name = "devmint_pl"
main = "./app/index.ts"
workers_dev = true
compatibility_flags = [ "nodejs_compat_v2", "global_fetch_strictly_public" ]
compatibility_date = "2025-04-09"

[assets]
binding = "ASSETS"
directory = "./build/client/"
run_worker_first = false

[observability]
enabled = true
head_sampling_rate = 1