name: 🥺 No Response

on:
  workflow_dispatch:
  schedule:
    # At 12:00.
    - cron: '0 12 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: 🥺 Handle Ghosting
        uses: actions/stale@v10
        with:
          days-before-stale: 7
          days-before-close: 3
          close-issue-message: >
            This issue has been automatically closed because we haven't received a
            response from the original author 🙈. This automation helps keep the issue
            tracker clean from issues that aren't actionable. Please reach out if you
            have more information for us! 🙂
          close-pr-message: >
            This PR has been automatically closed because we haven't received a
            response from the original author 🙈. This automation helps keep the issue
            tracker clean from PRs that aren't actionable. Please reach out if you
            have more information for us! 🙂
          stale-issue-label: needs-response
          stale-pr-label: needs-response
