name: Continous Integration

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  test_js:
    name: 🧪 CI for JS/TS
    uses: './.github/workflows/workflow-check-js.yml'
