name: 🧪 Check JS/TS

on:
  push:
    branches:
      - master

jobs:
  test_lint:
    name: 🧪 Verify code changes
    uses: ./.github/workflows/workflow-lint.yaml
    with:
      ESLINT_REPORTER: 'github-check'
