# GitHub Workflow: Check JS/TS
#
# This workflow is designed to perform various checks on JavaScript and TypeScript files in a project.
# It runs on every push to the repository and includes the following steps:
#
# 1. Checkout: Clones the repository to the runner.
# 2. Install pnpm: Sets up pnpm as the package manager for the project.
# 3. Setup Node: Configures the Node.js environment with the specified version and enables caching.
# 4. Install dependencies: Installs project dependencies using pnpm.
# 5. Find unused files: Runs the `pnpm unused` command to identify and report unused files.
# 6. Linting: Uses the `reviewdog-action-biome` to perform linting on the JavaScript and TypeScript files.
#
# This workflow is called as a workflow_call in other workflows, allowing for reusability and centralized management
name: Check JS/TS

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Find unused files
        run: pnpm unused

      - uses: mongolyy/reviewdog-action-biome
        with:
          reporter: github-pr-check
